✨ feat: Add wezterm and platform specific messaging

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,9 +1,15 @@
 #!/usr/bin/env bash
 
-if ! command -v zsh &> /dev/null
-then
-    echo "zsh could not be found, install it first"
-    exit 1
+PLATFORM=$(uname)
+
+if [[ "${PLATFORM}" == "Darwin" ]] && ! command -v brew &> /dev/null; then
+  echo "install homebrew with the following /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
+  exit 1
+fi
+
+if ! command -v zsh &> /dev/null; then
+  echo "zsh could not be found, install it first"
+  exit 1
 fi
 
 
@@ -29,4 +35,13 @@ ENV_CONFIG="install.conf.yaml"
   -c "${ENV_CONFIG}" \
   "${@}"
 
-echo "Recommend installing the following packages: fzf, autojump"
+echo "Recommend running the following commands:"
+echo "scripts/wezterm.sh"
+if [[ "${PLATFORM}" == "Darwin" ]]; then
+  echo "brew install antigen autojump fd fzf 1password-cli wezterm"
+  echo "brew install --cask font-meslo-lg-nerd-font"
+fi
+
+if [[ ! "${PLATFORM}" == "Darwin" ]]; then
+  echo "Recommend installing the following packages: fzf, autojump, wezterm"
+fi
