feat: Simplify setup
A better process that should work for both mac and linux.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,18 @@
 #!/usr/bin/env bash
 
+if ! command -v zsh &> /dev/null
+then
+    echo "zsh could not be found, install it first"
+    exit 1
+fi
+
+
 set -e
 
 # Dotbot vars
 DOTBOT_DIR="dotbot"
 DOTBOT_BIN="bin/dotbot"
 BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-P="${BASEDIR}/plugins"
 
 # Clone submodules
 cd "${BASEDIR}"
@@ -16,18 +22,11 @@ git submodule update --init --recursive
 # Remove existing zshrc if it's there
 rm ~/.zshrc || true
 
-# Install packages
-PACKAGE_CONFIG="packages-linux.conf.yaml"
-sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
-  -d "${BASEDIR}" \
-  -c "${PACKAGE_CONFIG}" \
-  -p "${P}/dotbot-apt/apt.py" \
-  "${@}"
-
-
 # Setup user env
-ENV_CONFIG="install-linux.conf.yaml"
+ENV_CONFIG="install.conf.yaml"
 "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
   -d "${BASEDIR}" \
   -c "${ENV_CONFIG}" \
   "${@}"
+
+echo "Recommend installing the following packages: fzf, autojump"
